# This is the Project setup. 
# The project consists of many Packages, in the vein of Cabal.

# Package resolver. Ensures that all dependencies work together in a nice way
resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/24/4.yaml

# https://docs.haskellstack.org/en/stable/yaml_configuration/#ghc-options
ghc-options:
    # All packages get these options
    "$locals": -Wall -threaded -rtsopts -with-rtsopts=-N

# User packages to be built. Each one is a folder with a Package inside it
# Each package is defined by package.yaml, which hpack translates into a .cabal-file
packages:
- day01
- day02
- day03
- day04
- day05
- day06
- day07
- day08
- day09
- day10
- day11
- day12
- day13
- day14
- day15
- day16
- day17
- day18
- day19
- day20
- day21
- day22
- util
