# This is the Project setup. 
# The project consists of many Packages, in the vein of Cabal.

# Package resolver. Ensures that all dependencies work together in a nice way
resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/18/0.yaml

# User packages to be built. Each one is a folder with a Package inside it
# Each package is defined by package.yaml, which hpack translates into a .cabal-file
packages:
- old
- day18
- day19
- day20
- day21
- util
