name: day19
version: 0.1.0.0

dependencies:
- base >= 4.7 && < 5
- util
- containers

library:
  source-dirs: src

executables:
  day19:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - day19

tests:
  day19-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - day19
    - hspec
