name: day21
version: 0.1.0.0

dependencies:
- base >= 4.7 && < 5
- util
- parsec

library:
  source-dirs: src

executables:
  day21:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - day21

tests:
  day21-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - day21
    - hspec
