name: day18
version: 0.1.0.0

dependencies:
- base >= 4.7 && < 5
- util

library:
  source-dirs: src

executables:
  day18:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - day18

tests:
  day18-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - day18
    - hspec
