name: day22
version: 0.1.0.0

dependencies:
- base >= 4.7 && < 5
- util
- lens
- containers

library:
  source-dirs: src

executables:
  day22:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - day22

tests:
  day22-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - day22
    - hspec
