name: util
version: 0.1.0.0

dependencies:
- base >= 4.7 && < 5
- mtl
- bytestring
- containers
- Cabal

library:
  source-dirs: src

tests:
  util-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - util
    - hspec
