# Pakcage.yaml is used by hpack to generate the cabal-file
name:                old
version:             0.1.0.0
github:              "el-hult/adventofcode2016"
license:             BSD3
author:              "Ludvig Hult"
maintainer:          "ludvig.hult@gmail.com"
copyright:           "2021 Ludvig Hult"
description:         Please see the README on GitHub at <https://github.com/el-hult/adventofcode2016#readme>

dependencies:
- base >= 4.7 && < 5
- parsec # welll.... parsing.
- util
- mtl
- containers # LOTS of stuff

library:
  source-dirs: src

executables:
  old:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - old

tests:
  old-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - old
    - HUnit
