name: day09
version: 0.1.0.0

dependencies:
- base >= 4.7 && < 5
- util

library:
  source-dirs: src
  dependencies:
  - parsec

executables:
  day09:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - day09

tests:
  day09-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - day09
    - HUnit
